// World currencies (ISO 4217). Plain data, no React Native imports, so the data layer and tests can use it.

export interface Currency {
  code: string;
  name: string;
  /** Prefix used when formatting money. Currencies without a well-known symbol use their code. */
  symbol: string;
}

// [code, name, symbol?]
const LIST: [string, string, string?][] = [
  ['AED', 'UAE Dirham', 'AED '],
  ['AFN', 'Afghan Afghani', '؋'],
  ['ALL', 'Albanian Lek'],
  ['AMD', 'Armenian Dram', '֏'],
  ['ANG', 'Netherlands Antillean Guilder'],
  ['AOA', 'Angolan Kwanza', 'Kz '],
  ['ARS', 'Argentine Peso'],
  ['AUD', 'Australian Dollar', 'A$'],
  ['AWG', 'Aruban Florin'],
  ['AZN', 'Azerbaijani Manat', '₼'],
  ['BAM', 'Bosnia-Herzegovina Mark', 'KM '],
  ['BBD', 'Barbadian Dollar'],
  ['BDT', 'Bangladeshi Taka', '৳'],
  ['BGN', 'Bulgarian Lev'],
  ['BHD', 'Bahraini Dinar'],
  ['BIF', 'Burundian Franc'],
  ['BMD', 'Bermudian Dollar'],
  ['BND', 'Brunei Dollar'],
  ['BOB', 'Bolivian Boliviano', 'Bs '],
  ['BRL', 'Brazilian Real', 'R$'],
  ['BSD', 'Bahamian Dollar'],
  ['BTN', 'Bhutanese Ngultrum'],
  ['BWP', 'Botswana Pula'],
  ['BYN', 'Belarusian Ruble'],
  ['BZD', 'Belize Dollar'],
  ['CAD', 'Canadian Dollar', 'C$'],
  ['CDF', 'Congolese Franc'],
  ['CHF', 'Swiss Franc', 'CHF '],
  ['CLP', 'Chilean Peso'],
  ['CNY', 'Chinese Yuan', 'CN¥'],
  ['COP', 'Colombian Peso'],
  ['CRC', 'Costa Rican Colón', '₡'],
  ['CUP', 'Cuban Peso'],
  ['CVE', 'Cape Verdean Escudo'],
  ['CZK', 'Czech Koruna', 'Kč '],
  ['DJF', 'Djiboutian Franc'],
  ['DKK', 'Danish Krone'],
  ['DOP', 'Dominican Peso', 'RD$'],
  ['DZD', 'Algerian Dinar'],
  ['EGP', 'Egyptian Pound', 'E£'],
  ['ERN', 'Eritrean Nakfa'],
  ['ETB', 'Ethiopian Birr'],
  ['EUR', 'Euro', '€'],
  ['FJD', 'Fijian Dollar'],
  ['FKP', 'Falkland Islands Pound'],
  ['GBP', 'British Pound', '£'],
  ['GEL', 'Georgian Lari', '₾'],
  ['GHS', 'Ghanaian Cedi', 'GH₵'],
  ['GIP', 'Gibraltar Pound'],
  ['GMD', 'Gambian Dalasi'],
  ['GNF', 'Guinean Franc'],
  ['GTQ', 'Guatemalan Quetzal'],
  ['GYD', 'Guyanese Dollar'],
  ['HKD', 'Hong Kong Dollar', 'HK$'],
  ['HNL', 'Honduran Lempira'],
  ['HTG', 'Haitian Gourde'],
  ['HUF', 'Hungarian Forint', 'Ft '],
  ['IDR', 'Indonesian Rupiah', 'Rp '],
  ['ILS', 'Israeli New Shekel', '₪'],
  ['INR', 'Indian Rupee', '₹'],
  ['IQD', 'Iraqi Dinar'],
  ['IRR', 'Iranian Rial'],
  ['ISK', 'Icelandic Króna'],
  ['JMD', 'Jamaican Dollar', 'J$'],
  ['JOD', 'Jordanian Dinar'],
  ['JPY', 'Japanese Yen', '¥'],
  ['KES', 'Kenyan Shilling', 'KSh '],
  ['KGS', 'Kyrgyzstani Som'],
  ['KHR', 'Cambodian Riel', '៛'],
  ['KMF', 'Comorian Franc'],
  ['KPW', 'North Korean Won'],
  ['KRW', 'South Korean Won', '₩'],
  ['KWD', 'Kuwaiti Dinar'],
  ['KYD', 'Cayman Islands Dollar'],
  ['KZT', 'Kazakhstani Tenge', '₸'],
  ['LAK', 'Lao Kip', '₭'],
  ['LBP', 'Lebanese Pound'],
  ['LKR', 'Sri Lankan Rupee', 'LKR '],
  ['LRD', 'Liberian Dollar'],
  ['LSL', 'Lesotho Loti'],
  ['LYD', 'Libyan Dinar'],
  ['MAD', 'Moroccan Dirham'],
  ['MDL', 'Moldovan Leu'],
  ['MGA', 'Malagasy Ariary'],
  ['MKD', 'Macedonian Denar'],
  ['MMK', 'Myanmar Kyat'],
  ['MNT', 'Mongolian Tögrög', '₮'],
  ['MOP', 'Macanese Pataca'],
  ['MRU', 'Mauritanian Ouguiya'],
  ['MUR', 'Mauritian Rupee'],
  ['MVR', 'Maldivian Rufiyaa'],
  ['MWK', 'Malawian Kwacha'],
  ['MXN', 'Mexican Peso', 'MX$'],
  ['MYR', 'Malaysian Ringgit', 'RM '],
  ['MZN', 'Mozambican Metical'],
  ['NAD', 'Namibian Dollar'],
  ['NGN', 'Nigerian Naira', '₦'],
  ['NIO', 'Nicaraguan Córdoba'],
  ['NOK', 'Norwegian Krone'],
  ['NPR', 'Nepalese Rupee', 'NPR '],
  ['NZD', 'New Zealand Dollar', 'NZ$'],
  ['OMR', 'Omani Rial'],
  ['PAB', 'Panamanian Balboa'],
  ['PEN', 'Peruvian Sol', 'S/ '],
  ['PGK', 'Papua New Guinean Kina'],
  ['PHP', 'Philippine Peso', '₱'],
  ['PKR', 'Pakistani Rupee', 'Rs '],
  ['PLN', 'Polish Złoty', 'zł '],
  ['PYG', 'Paraguayan Guaraní', '₲'],
  ['QAR', 'Qatari Riyal', 'QAR '],
  ['RON', 'Romanian Leu'],
  ['RSD', 'Serbian Dinar'],
  ['RUB', 'Russian Ruble', '₽'],
  ['RWF', 'Rwandan Franc'],
  ['SAR', 'Saudi Riyal', 'SAR '],
  ['SBD', 'Solomon Islands Dollar'],
  ['SCR', 'Seychellois Rupee'],
  ['SDG', 'Sudanese Pound'],
  ['SEK', 'Swedish Krona'],
  ['SGD', 'Singapore Dollar', 'S$'],
  ['SHP', 'Saint Helena Pound'],
  ['SLE', 'Sierra Leonean Leone'],
  ['SOS', 'Somali Shilling'],
  ['SRD', 'Surinamese Dollar'],
  ['SSP', 'South Sudanese Pound'],
  ['STN', 'São Tomé and Príncipe Dobra'],
  ['SYP', 'Syrian Pound'],
  ['SZL', 'Eswatini Lilangeni'],
  ['THB', 'Thai Baht', '฿'],
  ['TJS', 'Tajikistani Somoni'],
  ['TMT', 'Turkmenistani Manat'],
  ['TND', 'Tunisian Dinar'],
  ['TOP', 'Tongan Paʻanga'],
  ['TRY', 'Turkish Lira', '₺'],
  ['TTD', 'Trinidad and Tobago Dollar', 'TT$'],
  ['TWD', 'New Taiwan Dollar', 'NT$'],
  ['TZS', 'Tanzanian Shilling', 'TSh '],
  ['UAH', 'Ukrainian Hryvnia', '₴'],
  ['UGX', 'Ugandan Shilling', 'USh '],
  ['USD', 'US Dollar', '$'],
  ['UYU', 'Uruguayan Peso'],
  ['UZS', 'Uzbekistani Som'],
  ['VES', 'Venezuelan Bolívar'],
  ['VND', 'Vietnamese Đồng', '₫'],
  ['VUV', 'Vanuatu Vatu'],
  ['WST', 'Samoan Tālā'],
  ['XAF', 'Central African CFA Franc', 'FCFA '],
  ['XCD', 'East Caribbean Dollar', 'EC$'],
  ['XCG', 'Caribbean Guilder'],
  ['XOF', 'West African CFA Franc', 'CFA '],
  ['XPF', 'CFP Franc'],
  ['YER', 'Yemeni Rial'],
  ['ZAR', 'South African Rand', 'R '],
  ['ZMW', 'Zambian Kwacha'],
  ['ZWG', 'Zimbabwe Gold'],
];

const CURRENCY_LIST: Currency[] = LIST.map(([code, name, symbol]) => ({ code, name, symbol: symbol ?? `${code} ` }));
export const CURRENCIES = CURRENCY_LIST.map((c) => c.code);
/** Shown first in pickers; the rest are found by searching. */
export const POPULAR_CURRENCIES = ['PKR', 'USD', 'EUR', 'GBP', 'INR', 'AED', 'SAR', 'CAD', 'AUD', 'JPY', 'CNY', 'BDT', 'TRY', 'MYR', 'SGD'];

const BY_CODE = new Map(CURRENCY_LIST.map((c) => [c.code, c]));
export const findCurrency = (code: string) => BY_CODE.get(code);

/** Currencies matching a search by code or name, e.g. "rupee" or "lkr". */
export function searchCurrencies(query: string): Currency[] {
  const q = query.trim().toLowerCase();
  if (!q) return CURRENCY_LIST;
  return CURRENCY_LIST.filter((c) => c.code.toLowerCase().includes(q) || c.name.toLowerCase().includes(q));
}
